apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring        # el ns donde corre tu Alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: phylaxor
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
    - name: phylaxor
      webhook_configs:
      - url: "http://{{ .Values.ingress.service | default "ingest" }}.{{ .Values.namespace }}.svc.cluster.local:8080/alert"
        send_resolved: true
