apiVersion: apps/v1
kind: Deployment
metadata:
  name: enricher
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.replicas.enricher }}
  selector: { matchLabels: { app: enricher } }
  template:
    metadata: { labels: { app: enricher } }
    spec:
      serviceAccountName: phylaxor-sa
      volumes:
      - name: ctx
        configMap: { name: enricher-context }
      containers:
      - name: enricher
        image: "{{ .Values.images.enricher.repository }}:{{ .Values.images.enricher.tag }}"
        imagePullPolicy: {{ .Values.images.enricher.pullPolicy }}
        volumeMounts: [{ name: ctx, mountPath: /data }]
        env:
        - name: REDIS_HOST
          value: "{{ .Values.serviceConnections.redis.host }}"
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        resources: {{- toYaml .Values.resources.enricher | nindent 10 }}