apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.decision }}
  selector: { matchLabels: { app: decision } }
  template:
    metadata: { labels: { app: decision } }
    spec:
      serviceAccountName: phylaxor-sa
      containers:
      - name: decision
        image: "{{ .Values.images.decision.repository }}:{{ .Values.images.decision.tag }}"
        imagePullPolicy: {{ .Values.images.decision.pullPolicy }}
        env:
        - name: REDIS_HOST
          value: "{{ .Values.serviceConnections.redis.host }}"
        - name: PG_DSN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.existingSecret }}
              key:  {{ .Values.db.dsnKey }}
        - name: NOTIFIER_URL
          value: "http://notifier.{{ .Values.namespace }}.svc.cluster.local:8082/send"
