apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.replicas.ingest }}
  selector: { matchLabels: { app: ingest } }
  template:
    metadata: { labels: { app: ingest } }
    spec:
      serviceAccountName: phylaxor-sa
      containers:
      - name: ingest
        image: "{{ .Values.images.ingest.repository }}:{{ .Values.images.ingest.tag }}"
        imagePullPolicy: {{ .Values.images.ingest.pullPolicy }}
        ports: [{ containerPort: 8080 }]
        env:
        - name: REDIS_HOST
          value: "{{ .Values.serviceConnections.redis.host }}"
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        resources: {{- toYaml .Values.resources.ingest | nindent 10 }}