apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: phylaxor-db
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:16
              envFrom:
                - secretRef:
                    name: postgres-auth
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -e
                  TS=$(date +%F_%H-%M-%S)
                  mkdir -p /backups/$TS
                  pg_dump -h postgres -U "$POSTGRES_USER" -d "$POSTGRES_DB" > /backups/$TS/backup.sql
              volumeMounts:
                - name: backup-volume
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: data-postgres-0
