namespace: phylaxor
namespaceCreate: false
manualAlertManagerConfig: false # OpenShift usa su propio AlertManager
images:
  ingest:
    repository: ghcr.io/slavikblxt4/phylaxor-ingest
    tag: "r53-b6a1a36" # ingest
    pullPolicy: IfNotPresent
  enricher:
    repository: ghcr.io/slavikblxt4/phylaxor-enricher
    tag: "r52-a963c10" # enricher
    pullPolicy: IfNotPresent
  decision:
    repository: ghcr.io/slavikblxt4/phylaxor-decision
    tag: "r56-d4299e7" # decision
    pullPolicy: IfNotPresent
  notifier:
    repository: ghcr.io/slavikblxt4/phylaxor-notifier
    tag: "r52-a963c10" # notifier
    pullPolicy: IfNotPresent
  feedback:
    repository: ghcr.io/slavikblxt4/phylaxor-feedback
    tag: "r43-c862a77" # feedback
    pullPolicy: IfNotPresent
  feedback_gateway:
    repository: ghcr.io/slavikblxt4/phylaxor-feedback_gateway
    tag: "r52-a963c10" # feedback_gateway
    pullPolicy: IfNotPresent
ingress:
  service: ingest
imagePullSecrets:
  - ghcr-creds
replicas:
  feedback_gateway: 1
  feedback: 1
  ingest: 1
  enricher: 1
  decision: 1
  notifier: 1
resources:
  ingest: {requests: {cpu: 100m, memory: 128Mi}, limits: {cpu: 500m, memory: 256Mi}}
  enricher: {requests: {cpu: 50m, memory: 64Mi}, limits: {cpu: 200m, memory: 128Mi}}
  decision: {requests: {cpu: 150m, memory: 256Mi}, limits: {cpu: 500m, memory: 512Mi}}
  notifier: {requests: {cpu: 50m, memory: 64Mi}, limits: {cpu: 200m, memory: 128Mi}}
  feedback_gateway: {requests: {cpu: 20m, memory: 32Mi}, limits: {cpu: 100m, memory: 64Mi}}
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  seccompProfile:
    type: RuntimeDefault
logging:
  mode: "none" # modes: none | loki | podlogs
  eventsEnabled: true
  maxLines: 500
  maxBytes: 100000
  lookbackSeconds: 300
  timeout: 5
db:
  existingSecret: "phylaxor-db" # Secret con la DSN
  dsnKey: "dsn"
telegram:
  existingSecret: "phylaxor-telegram"
  tokenKey: "token"
  chatIdKey: "chat_id"
env:
  enricherContext:
    platform: "k8s"
    cluster: "minikube"
    version: "1.32"
    storage: "hostpath"
    operators: ["prom-operator"]
expose:
  type: none # none | ingress
  host: phylaxor.localtest.me
  ingressClassName: nginx
serviceConnections:
  redis:
    host: "redis.phylaxor-db.svc.cluster.local"
    port: 6379
  postgres:
    host: "postgres.phylaxor-db.svc.cluster.local"
    port: 5432
