namespace: phylaxor

images:
  ingest:
    repository: ghcr.io/slavikblxt4/phylaxor-ingest
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  enricher:
    repository: ghcr.io/slavikblxt4/phylaxor-enricher
    tag: "0.1.1"
    pullPolicy: IfNotPresent
  decision:
    repository: ghcr.io/slavikblxt4/phylaxor-decision
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  notifier:
    repository: ghcr.io/slavikblxt4/phylaxor-notifier
    tag: "0.1.0"
    pullPolicy: IfNotPresent


imagePullSecrets:
  - ghcr-creds


replicas:
  ingest: 1
  enricher: 1
  decision: 1
  notifier: 1

resources:
  ingest: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: 500m, memory: 256Mi } }
  enricher: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 200m, memory: 128Mi } }
  decision: { requests: { cpu: 150m, memory: 256Mi }, limits: { cpu: 500m, memory: 512Mi } }
  notifier: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 200m, memory: 128Mi } }

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile: { type: RuntimeDefault }
  capabilities: { drop: ["ALL"] }

redis:
  enabled: true
  image: redis:7
  storage:
    enabled: false
    size: 1Gi
    storageClassName: ""

db:
  existingSecret: "phylaxor-db"   # Secret con la DSN
  dsnKey: "dsn"

postgres:
  enabled: true            # si quieres Postgres in-cluster para DEV
  image: postgres:16
  storage:
    size: 5Gi
    storageClassName: standard
  # Secret con usuario/clave/db para el contenedor de Postgres (no lo gestiona Helm)
  authSecretName: "postgres-auth"
  # init SQL (esto sí puede ir en ConfigMap)
  initSql: |
    create table if not exists alerts(...);
    create table if not exists decisions(...);
    create table if not exists feedback(...);

telegram:
  existingSecret: "phylaxor-telegram"
  tokenKey: "token"
  chatIdKey: "chat_id"

env:
  enricherContext:
    platform: "k8s"
    cluster: "minikube"
    version: "1.32"
    storage: "hostpath"
    operators: ["prom-operator"]

expose:
  type: none              # none | ingress
  host: phylaxor.localtest.me
  ingressClassName: nginx
