apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: phylaxor-sa
  namespace: {{ .Values.namespace }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
