apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "phylaxor.sa" "enricher" }}
      namespace: {{ .Release.Namespace }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "phylaxor.sa" "notifier" }}
      namespace: {{ .Release.Namespace }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "phylaxor.sa" "ingest" }}
      namespace: {{ .Release.Namespace }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "phylaxor.sa" "decision" }}
      namespace: {{ .Release.Namespace }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "phylaxor.sa" "feedback" }}
      namespace: {{ .Release.Namespace }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "phylaxor.sa" "feedback-gateway" }}
      namespace: {{ .Release.Namespace }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "phylaxor.sa" "brain-gateway" }}
      namespace: {{ .Release.Namespace }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
