apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: phylaxordb-gitops-manager-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: phylaxor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: phylaxor-gitops-manager
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
