apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phylaxor-enricher-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "phylaxor.sa" "enricher" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: phylaxor-enricher-role
