apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: phylaxor-enricher-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["get","list","watch"]
{{- if eq (.Values.logs.mode | default .Values.logging.mode) "podlogs" }}
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
{{- end }}